# For local development only.

version: '3'

services:
  proxy-psr3-8.0:
    container_name: proxy-psr3-8.0
    hostname: proxy-psr3-80
    build: docker/8.0
    working_dir: /srv
    volumes:
      - .:/srv

  proxy-psr3-8.1:
    container_name: proxy-psr3-8.1
    hostname: proxy-psr3-81
    build: docker/8.1
    working_dir: /srv
    volumes:
      - .:/srv

  proxy-psr3-8.2:
    container_name: proxy-psr3-8.2
    hostname: proxy-psr3-82
    build: docker/8.2
    working_dir: /srv
    volumes:
      - .:/srv

  proxy-psr3-8.3:
    container_name: proxy-psr3-8.3
    hostname: proxy-psr3-83
    build: docker/8.3
    working_dir: /srv
    volumes:
      - .:/srv
